### ISSUE TITLE
Link for straw man GraphBLAS proposal is broken

### ISSUE THREAD

**Issue by Robyt3** [GraphBLAS/graphblas.github.io#6]
> A straw man proposal for the GraphBLAS can be found [here](http://gauss.cs.ucsb.edu/~aydin/combblas-r2.pdf)

**Comment by DrTimothyAldenDavis** [comment]
That should be a link to @aydinbuluc's page, I think: https://people.eecs.berkeley.edu/~aydin/combblas-r2.pdf

**Comment by DrTimothyAldenDavis** [comment]
The link is fixed now.  Thanks for catching it.
